# Form implementation generated from reading ui file './ui/save_v.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Save_v(object):
    def setupUi(self, MainWindow_Save_v):
        MainWindow_Save_v.setObjectName("MainWindow_Save_v")
        MainWindow_Save_v.resize(368, 198)
        self.centralwidget = QtWidgets.QWidget(MainWindow_Save_v)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_input = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.verticalLayout.addWidget(self.groupBox)
        self.plainTextEdit_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_output.setObjectName("plainTextEdit_output")
        self.verticalLayout.addWidget(self.plainTextEdit_output)
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        MainWindow_Save_v.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_Save_v)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 368, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_Save_v.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Save_v)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Save_v.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Save_v)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Save_v)

    def retranslateUi(self, MainWindow_Save_v):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Save_v.setWindowTitle(_translate("MainWindow_Save_v", "Save v"))
        self.groupBox.setTitle(_translate("MainWindow_Save_v", "Input"))
        self.pushButton_add.setText(_translate("MainWindow_Save_v", "Add"))
